-- ============================================
-- ClipGrove: 首批50款AI视频工具数据
-- ============================================

-- 清空旧数据
DELETE FROM web_navigation;

-- 1. 文字转视频 (Text-to-Video)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('runway', 'Runway', 'Runway is the leading AI video generation platform. Create stunning videos from text prompts, images, or existing footage. Used by millions of creators worldwide.', '## Runway Gen-3 Alpha\n\nRunway is the industry-leading AI video generation platform.\n\n### Key Features\n- Text-to-video generation\n- Image-to-video\n- Video-to-video transformation\n- Motion Brush for precise control\n- Green Screen and background removal\n\n### Pricing\n- Free: 125 credits/month\n- Standard: $12/month\n- Pro: $28/month\n- Unlimited: $76/month', 'https://runwayml.com', 'https://img.tap4.ai/tools/runway.png', 'https://img.tap4.ai/tools/runway-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 9, 'text-to-video,ai-video', 'text-to-video'),
('pika', 'Pika', 'Pika is an AI video generator that turns text and images into stunning videos. Simple, fast, and creative video generation for everyone.', '## Pika 2.0\n\nPika is a user-friendly AI video generation platform.\n\n### Key Features\n- Text-to-video\n- Image-to-video\n- Video style transfer\n- Lip sync\n- Sound effects generation\n\n### Pricing\n- Free: 250 credits/month\n- Basic: $8/month\n- Unlimited: $28/month', 'https://pika.art', 'https://img.tap4.ai/tools/pika.png', 'https://img.tap4.ai/tools/pika-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'text-to-video', 'text-to-video'),
('sora', 'Sora', 'OpenAI Sora is a breakthrough AI video generation model that creates realistic videos from text descriptions with unprecedented quality.', '## OpenAI Sora\n\nSora is OpenAI''s revolutionary text-to-video model.\n\n### Key Features\n- High-quality video generation\n- Complex scene understanding\n- Realistic physics simulation\n- Long-form video support\n- Multi-character scenes\n\n### Pricing\n- Included with ChatGPT Plus/Pro subscription', 'https://sora.com', 'https://img.tap4.ai/tools/sora.png', 'https://img.tap4.ai/tools/sora-thumb.png', '{"pricing":"Subscription","platform":"Web"}', NOW(), 10, 'text-to-video,openai', 'text-to-video'),
('kling', 'Kling AI', 'Kling AI by Kuaishou is a powerful AI video generation model. Create realistic videos up to 2 minutes long from text prompts.', '## Kling AI\n\nKling AI delivers impressive video generation quality.\n\n### Key Features\n- Text-to-video (up to 2 min)\n- Image-to-video\n- Video extension\n- High-quality output\n\n### Pricing\n- Free trial available\n- Paid plans from $5/month', 'https://klingai.com', 'https://img.tap4.ai/tools/kling.png', 'https://img.tap4.ai/tools/kling-thumb.png', '{"pricing":"Freemium","platform":"Web,App"}', NOW(), 9, 'text-to-video', 'text-to-video'),
('vidu', 'Vidu', 'Vidu is a next-gen AI video generation platform. Create high-quality videos from text and images with advanced AI technology.', '## Vidu\n\nVidu offers cutting-edge AI video generation.\n\n### Key Features\n- Text-to-video\n- Image-to-video\n- Reference image mode\n- High consistency generation\n\n### Pricing\n- Free tier available\n- Pro plans from $10/month', 'https://www.vidu.studio', 'https://img.tap4.ai/tools/vidu.png', 'https://img.tap4.ai/tools/vidu-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'text-to-video', 'text-to-video'),
('hailuo', 'Hailuo AI', 'Hailuo AI by MiniMax is a powerful AI video generation tool. Create stunning videos from text with impressive quality and speed.', '## Hailuo AI\n\nHailuo is a fast and efficient AI video generator.\n\n### Key Features\n- Fast text-to-video\n- High-quality output\n- Simple interface\n\n### Pricing\n- Free to use', 'https://hailuoai.video', 'https://img.tap4.ai/tools/hailuo.png', 'https://img.tap4.ai/tools/hailuo-thumb.png', '{"pricing":"Free","platform":"Web"}', NOW(), 7, 'text-to-video', 'text-to-video'),
('pixverse', 'PixVerse', 'PixVerse is an AI video generation platform that creates stunning videos from text and images. Support for multiple styles and effects.', '## PixVerse\n\nPixVerse offers versatile AI video generation.\n\n### Key Features\n- Text-to-video\n- Image-to-video\n- Anime style support\n- Realistic style support\n\n### Pricing\n- Free tier available\n- Premium plans from $9/month', 'https://pixverse.ai', 'https://img.tap4.ai/tools/pixverse.png', 'https://img.tap4.ai/tools/pixverse-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'text-to-video', 'text-to-video');

-- 2. AI动画 (AI Animation)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('kaiber', 'Kaiber', 'Kaiber is an AI creative studio for generating animations and videos. Create stunning animated content with AI-powered tools.', '## Kaiber\n\nKaiber is an AI animation and video generation platform.\n\n### Key Features\n- AI animation generation\n- Style transfer\n- Audio reactivity\n- Multiple animation styles\n\n### Pricing\n- Free trial\n- Pro: $10/month\n- Artist: $25/month', 'https://kaiber.ai', 'https://img.tap4.ai/tools/kaiber.png', 'https://img.tap4.ai/tools/kaiber-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-animation', 'ai-animation'),
('deepmotion', 'DeepMotion', 'DeepMotion creates AI-powered 3D animations from videos. Turn any video into animated 3D characters with realistic motion.', '## DeepMotion\n\nDeepMotion specializes in AI motion capture and 3D animation.\n\n### Key Features\n- Video to 3D animation\n- AI motion capture\n- Real-time character animation\n- Body tracking\n\n### Pricing\n- Free: 3 animations/month\n- Starter: $17/month\n- Professional: $67/month', 'https://deepmotion.com', 'https://img.tap4.ai/tools/deepmotion.png', 'https://img.tap4.ai/tools/deepmotion-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-animation', 'ai-animation'),
('plask', 'Plask', 'Plask is an AI-powered motion capture and animation tool. Create professional animations from video captures easily.', '## Plask\n\nPlask offers AI motion capture animation tools.\n\n### Key Features\n- AI motion capture from video\n- 3D animation editing\n- Browser-based workflow\n- Export to major 3D formats\n\n### Pricing\n- Free tier available\n- Pro: $50/month', 'https://plask.ai', 'https://img.tap4.ai/tools/plask.png', 'https://img.tap4.ai/tools/plask-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'ai-animation', 'ai-animation'),
('cascadeur', 'Cascadeur', 'Cascadeur is an AI-assisted 3D animation software. Create realistic character animations with physics-based AI tools.', '## Cascadeur\n\nCascadeur revolutionizes 3D character animation with AI.\n\n### Key Features\n- AI-assisted animation\n- Physics-based auto-posing\n- Realistic motion generation\n- Professional animation tools\n\n### Pricing\n- Free for indie developers\n- Pro: $300/year', 'https://cascadeur.com', 'https://img.tap4.ai/tools/cascadeur.png', 'https://img.tap4.ai/tools/cascadeur-thumb.png', '{"pricing":"Freemium","platform":"Desktop"}', NOW(), 8, 'ai-animation', 'ai-animation'),
('animaker', 'Animaker', 'Animaker is an AI-powered animation and video making platform. Create animated videos, presentations, and GIFs with ease.', '## Animaker\n\nAnimaker is a comprehensive animation platform.\n\n### Key Features\n- AI animation creation\n- 2D character animation\n- Whiteboard animations\n- Infographic videos\n- Text-to-animation\n\n### Pricing\n- Free: limited features\n- Basic: $12.50/month\n- Pro: $39/month', 'https://www.animaker.com', 'https://img.tap4.ai/tools/animaker.png', 'https://img.tap4.ai/tools/animaker-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'ai-animation', 'ai-animation'),
('motionity', 'Motionity', 'Motionity is a free and open-source motion graphics editor. Create animations with a web-based, AI-assisted interface.', '## Motionity\n\nMotionity is a free, open-source animation editor.\n\n### Key Features\n- Web-based motion graphics\n- Keyframe animation\n- AI-assisted design\n- Open source\n\n### Pricing\n- Free and open source', 'https://motionity.app', 'https://img.tap4.ai/tools/motionity.png', 'https://img.tap4.ai/tools/motionity-thumb.png', '{"pricing":"Free","platform":"Web"}', NOW(), 7, 'ai-animation', 'ai-animation');

-- 3. AI数字人 (AI Avatar)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('heygen', 'HeyGen', 'HeyGen is the leading AI video platform for creating spokesperson videos with realistic AI avatars. Perfect for business and marketing.', '## HeyGen\n\nHeyGen creates AI avatar videos for business.\n\n### Key Features\n- 100+ AI avatars\n- Text-to-speech in 40+ languages\n- Custom avatar creation\n- Video translation\n- API access\n\n### Pricing\n- Free: 1 credit/month\n- Creator: $24/month\n- Business: $72/month', 'https://www.heygen.com', 'https://img.tap4.ai/tools/heygen.png', 'https://img.tap4.ai/tools/heygen-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 9, 'ai-avatar', 'ai-avatar'),
('synthesia', 'Synthesia', 'Synthesia is an AI video generation platform for creating professional videos with AI avatars. No cameras or studios needed.', '## Synthesia\n\nSynthesia is the #1 AI video platform for enterprises.\n\n### Key Features\n- 140+ AI avatars\n- 120+ languages\n- Custom avatar creation\n- Video templates\n- Team collaboration\n\n### Pricing\n- Starter: $22/month\n- Creator: $67/month\n- Enterprise: Custom', 'https://www.synthesia.io', 'https://img.tap4.ai/tools/synthesia.png', 'https://img.tap4.ai/tools/synthesia-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 9, 'ai-avatar', 'ai-avatar'),
('d-id', 'D-ID', 'D-ID creates AI-powered digital humans and talking avatars. Transform photos and text into engaging video content.', '## D-ID\n\nD-ID specializes in AI digital humans.\n\n### Key Features\n- Photo-to-talking-avatar\n- AI video generation\n- Real-time streaming avatars\n- API integration\n\n### Pricing\n- Trial: 5 minutes free\n- Basic: $5.99/month\n- Pro: $49.99/month', 'https://www.d-id.com', 'https://img.tap4.ai/tools/did.png', 'https://img.tap4.ai/tools/did-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-avatar', 'ai-avatar'),
('elai', 'Elai.io', 'Elai.io is an AI video generator with digital avatars. Create training videos, marketing content, and product demos in minutes.', '## Elai.io\n\nElai is a powerful AI avatar video platform.\n\n### Key Features\n- 80+ AI avatars\n- 75+ languages\n- PPT-to-video\n- Auto-subtitles\n- Brand kit\n\n### Pricing\n- Basic: $29/month\n- Advanced: $99/month\n- Custom: Enterprise', 'https://elai.io', 'https://img.tap4.ai/tools/elai.png', 'https://img.tap4.ai/tools/elai-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 7, 'ai-avatar', 'ai-avatar'),
('colossyan', 'Colossyan', 'Colossyan is an AI video platform for workplace learning. Create training videos with AI avatars in multiple languages.', '## Colossyan\n\nColossyan focuses on AI training videos.\n\n### Key Features\n- AI avatars for training\n- Multi-language support\n- SCORM export\n- Interactive videos\n\n### Pricing\n- Starter: $28/month\n- Pro: $87/month\n- Enterprise: Custom', 'https://www.colossyan.com', 'https://img.tap4.ai/tools/colossyan.png', 'https://img.tap4.ai/tools/colossyan-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 7, 'ai-avatar', 'ai-avatar'),
('studio-d-id', 'Studio D-ID', 'Studio D-ID is a creative platform for generating AI-powered talking avatars. Perfect for content creators and marketers.', '## Studio D-ID\n\nStudio D-ID is the creative suite for AI avatars.\n\n### Key Features\n- Creative avatar studio\n- Custom backgrounds\n- Voice customization\n- Batch generation\n\n### Pricing\n- Free trial\n- Creative: $15/month\n- Business: $50/month', 'https://studio.d-id.com', 'https://img.tap4.ai/tools/studio-did.png', 'https://img.tap4.ai/tools/studio-did-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'ai-avatar', 'ai-avatar');

-- 4. AI视频编辑 (AI Video Editing)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('descript', 'Descript', 'Descript is an all-in-one AI video and audio editor. Edit videos by editing text, with AI-powered transcription and effects.', '## Descript\n\nDescript revolutionizes video editing with AI.\n\n### Key Features\n- Text-based video editing\n- AI transcription\n- AI voice cloning\n- Screen recording\n- Filler word removal\n\n### Pricing\n- Free: limited features\n- Creator: $12/month\n- Business: $24/month', 'https://www.descript.com', 'https://img.tap4.ai/tools/descript.png', 'https://img.tap4.ai/tools/descript-thumb.png', '{"pricing":"Freemium","platform":"Desktop,Web"}', NOW(), 9, 'ai-video-editing', 'ai-video-editing'),
('capcut', 'CapCut', 'CapCut is a free AI-powered video editor. Auto-captions, background removal, AI effects, and more for creators.', '## CapCut\n\nCapCut is the most popular free video editor.\n\n### Key Features\n- AI auto-captions\n- Background removal\n- AI effects and filters\n- Text-to-speech\n- Motion tracking\n\n### Pricing\n- Free\n- Pro: $7.99/month', 'https://www.capcut.com', 'https://img.tap4.ai/tools/capcut.png', 'https://img.tap4.ai/tools/capcut-thumb.png', '{"pricing":"Freemium","platform":"Desktop,Mobile,Web"}', NOW(), 9, 'ai-video-editing', 'ai-video-editing'),
('invideo', 'InVideo AI', 'InVideo AI creates videos from text prompts. Generate complete videos with AI voiceover, stock footage, and music.', '## InVideo AI\n\nInVideo AI generates complete videos from text.\n\n### Key Features\n- Text-to-video generation\n- AI voiceover\n- Stock footage library\n- Video templates\n- Brand customization\n\n### Pricing\n- Free: 10 min/week\n- Plus: $20/month\n- Max: $60/month', 'https://invideo.io', 'https://img.tap4.ai/tools/invideo.png', 'https://img.tap4.ai/tools/invideo-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-video-editing', 'ai-video-editing'),
('wisecut', 'Wisecut', 'Wisecut is an AI video editor that automatically cuts silences, adds subtitles, and creates engaging short videos.', '## Wisecut\n\nWisecut automates video editing with AI.\n\n### Key Features\n- Auto silence removal\n- Auto subtitles\n- AI background music\n- Smart editing\n\n### Pricing\n- Free: limited\n- Starter: $15/month\n- Professional: $57/month', 'https://www.wisecut.video', 'https://img.tap4.ai/tools/wisecut.png', 'https://img.tap4.ai/tools/wisecut-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'ai-video-editing', 'ai-video-editing'),
('pictory', 'Pictory', 'Pictory is an AI video editor that turns long-form content into short, shareable videos. Perfect for repurposing content.', '## Pictory\n\nPictory repurposes content with AI video editing.\n\n### Key Features\n- Blog-to-video\n- Auto-captioning\n- AI highlights extraction\n- Brand templates\n\n### Pricing\n- Starter: $19/month\n- Professional: $39/month\n- Teams: $99/month', 'https://pictory.ai', 'https://img.tap4.ai/tools/pictory.png', 'https://img.tap4.ai/tools/pictory-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 7, 'ai-video-editing', 'ai-video-editing'),
('opencut', 'OpenCut', 'OpenCut is an AI-powered video editor that simplifies the editing process. Smart cuts, effects, and fast rendering.', '## OpenCut\n\nOpenCut is an efficient AI video editor.\n\n### Key Features\n- AI-powered editing\n- Smart cut detection\n- Auto effects\n- Fast rendering\n\n### Pricing\n- Free tier\n- Pro: $12/month', 'https://opencut.ai', 'https://img.tap4.ai/tools/opencut.png', 'https://img.tap4.ai/tools/opencut-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 6, 'ai-video-editing', 'ai-video-editing'),
('veed', 'VEED.io', 'VEED.io is an online AI video editor. Create professional videos with auto-subtitles, effects, and easy editing tools.', '## VEED.io\n\nVEED.io is a popular online video editor.\n\n### Key Features\n- Auto subtitles\n- AI background removal\n- Screen recording\n- Video effects\n- Team collaboration\n\n### Pricing\n- Free: limited\n- Basic: $12/month\n- Pro: $24/month', 'https://www.veed.io', 'https://img.tap4.ai/tools/veed.png', 'https://img.tap4.ai/tools/veed-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-video-editing', 'ai-video-editing');

-- 5. AI短视频 (AI Shorts)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('opus', 'Opus Clip', 'Opus Clip is an AI video clipping tool that turns long videos into viral short clips. Perfect for YouTube Shorts and TikTok.', '## Opus Clip\n\nOpus Clip is the #1 AI video clipping tool.\n\n### Key Features\n- AI viral moment detection\n- Auto-face tracking\n- Auto captions\n- Multi-platform formatting\n\n### Pricing\n- Free: 5 hours/month\n- Pro: $19/month\n- Business: $114/month', 'https://www.opus.pro', 'https://img.tap4.ai/tools/opus.png', 'https://img.tap4.ai/tools/opus-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 9, 'ai-shorts', 'ai-shorts'),
('clipchamp', 'Clipchamp', 'Clipchamp by Microsoft is a free AI video editor. Create short videos, auto-captions, and social media content easily.', '## Clipchamp\n\nClipchamp is Microsoft''s video editor.\n\n### Key Features\n- AI auto-captions\n- Text-to-speech\n- Stock library\n- Screen recording\n- Social media templates\n\n### Pricing\n- Free\n- Premium: $11.99/month', 'https://clipchamp.com', 'https://img.tap4.ai/tools/clipchamp.png', 'https://img.tap4.ai/tools/clipchamp-thumb.png', '{"pricing":"Freemium","platform":"Web,Desktop"}', NOW(), 8, 'ai-shorts', 'ai-shorts'),
('submagic', 'Submagic', 'Submagic creates AI captions and effects for short videos. Boost engagement with dynamic subtitles and transitions.', '## Submagic\n\nSubmagic enhances short videos with AI.\n\n### Key Features\n- AI dynamic captions\n- Auto emoji insertion\n- B-roll suggestions\n- Trendy transitions\n\n### Pricing\n- Starter: $16/month\n- Business: $40/month', 'https://www.submagic.co', 'https://img.tap4.ai/tools/submagic.png', 'https://img.tap4.ai/tools/submagic-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 8, 'ai-shorts', 'ai-shorts'),
('fliki', 'Fliki', 'Fliki turns text into videos with AI voices. Create short-form videos for social media, YouTube, and marketing.', '## Fliki\n\nFliki is a text-to-video AI platform.\n\n### Key Features\n- Text-to-video\n- 900+ AI voices\n- 75+ languages\n- Blog-to-video\n- Social media formats\n\n### Pricing\n- Free: 5 min audio/month\n- Standard: $8/month\n- Premium: $16/month', 'https://fliki.ai', 'https://img.tap4.ai/tools/fliki.png', 'https://img.tap4.ai/tools/fliki-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-shorts', 'ai-shorts'),
('munch', 'Munch', 'Munch is an AI content repurposing platform. Extract the most engaging moments from long videos for social media.', '## Munch\n\nMunch repurposes content with AI.\n\n### Key Features\n- AI content analysis\n- Auto clip extraction\n- Multi-platform optimization\n- Trend analysis\n\n### Pricing\n- Free trial\n- Pro: $49/month\n- Enterprise: Custom', 'https://www.getmunch.com', 'https://img.tap4.ai/tools/munch.png', 'https://img.tap4.ai/tools/munch-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'ai-shorts', 'ai-shorts'),
('klap', 'Klap', 'Klap is an AI tool that turns YouTube videos into TikTok and Reels-ready clips. Auto-generate viral shorts.', '## Klap\n\nKlap automates short-form video creation.\n\n### Key Features\n- AI clip generation\n- Auto face detection\n- Dynamic captions\n- One-click export\n\n### Pricing\n- Free tier\n- Pro: $23/month', 'https://klap.app', 'https://img.tap4.ai/tools/klap.png', 'https://img.tap4.ai/tools/klap-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'ai-shorts', 'ai-shorts');

-- 6. 图转视频 (Image-to-Video)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('leiapix', 'LeiaPix', 'LeiaPix converts 2D images into 3D animations. Add depth and motion to any photo with AI technology.', '## LeiaPix\n\nLeiaPix brings 2D images to life with 3D animation.\n\n### Key Features\n- 2D to 3D animation\n- Depth map generation\n- Custom motion paths\n- Export to GIF/MP4\n\n### Pricing\n- Free', 'https://convert.leiapix.com', 'https://img.tap4.ai/tools/leiapix.png', 'https://img.tap4.ai/tools/leiapix-thumb.png', '{"pricing":"Free","platform":"Web"}', NOW(), 8, 'image-to-video', 'image-to-video'),
('genmo', 'Genmo', 'Genmo is an AI creative tool for generating videos from images and text. Create stunning visual content with AI.', '## Genmo\n\nGenmo generates creative videos from images.\n\n### Key Features\n- Image-to-video\n- Video generation\n- Creative AI tools\n\n### Pricing\n- Free daily credits\n- Premium available', 'https://www.genmo.ai', 'https://img.tap4.ai/tools/genmo.png', 'https://img.tap4.ai/tools/genmo-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'image-to-video', 'image-to-video'),
('immerse', 'Immerse', 'Immerse converts static images into immersive 3D videos. Create depth and perspective effects with AI.', '## Immerse\n\nImmerse brings images to life with depth.\n\n### Key Features\n- Image-to-3D video\n- Depth perception AI\n- Cinematic effects\n\n### Pricing\n- Free tier\n- Pro: $9.99/month', 'https://immerse.ai', 'https://img.tap4.ai/tools/immerse.png', 'https://img.tap4.ai/tools/immerse-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 6, 'image-to-video', 'image-to-video'),
('motionleap', 'Motionleap', 'Motionleap animates photos with AI. Add motion to specific elements, create cinemagraphs, and share on social media.', '## Motionleap\n\nMotionleap animates your photos with AI.\n\n### Key Features\n- Element animation\n- Sky replacement\n- Overlay effects\n- Cinemagraph creation\n\n### Pricing\n- Free with watermark\n- Pro: $5.99/month', 'https://motionleap.com', 'https://img.tap4.ai/tools/motionleap.png', 'https://img.tap4.ai/tools/motionleap-thumb.png', '{"pricing":"Freemium","platform":"Mobile"}', NOW(), 7, 'image-to-video', 'image-to-video'),
('deoldify', 'DeOldify', 'DeOldify is an AI tool for colorizing and restoring old black-and-white videos and photos. Bring history to life.', '## DeOldify\n\nDeOldify colorizes old videos with AI.\n\n### Key Features\n- Video colorization\n- Photo colorization\n- AI restoration\n- Open source\n\n### Pricing\n- Free and open source', 'https://deoldify.ai', 'https://img.tap4.ai/tools/deoldify.png', 'https://img.tap4.ai/tools/deoldify-thumb.png', '{"pricing":"Free","platform":"Web"}', NOW(), 7, 'image-to-video', 'image-to-video');

-- 7. AI配音 (AI Voiceover)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('elevenlabs', 'ElevenLabs', 'ElevenLabs is the leading AI voice and text-to-speech platform. Generate realistic AI voices for videos, podcasts, and more.', '## ElevenLabs\n\nElevenLabs is the #1 AI voice platform.\n\n### Key Features\n- Text-to-speech\n- Voice cloning\n- 29 languages\n- Voice design\n- Dubbing\n\n### Pricing\n- Free: 10k chars/month\n- Starter: $5/month\n- Creator: $22/month\n- Pro: $99/month', 'https://elevenlabs.io', 'https://img.tap4.ai/tools/elevenlabs.png', 'https://img.tap4.ai/tools/elevenlabs-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 10, 'ai-voiceover', 'ai-voiceover'),
('murf', 'Murf AI', 'Murf AI is a versatile AI voice generator. Create studio-quality voiceovers for videos, presentations, and podcasts.', '## Murf AI\n\nMurf generates professional AI voiceovers.\n\n### Key Features\n- 120+ AI voices\n- 20+ languages\n- Voice customization\n- Timeline editor\n- Music library\n\n### Pricing\n- Free: 10 min\n- Basic: $19/month\n- Pro: $26/month', 'https://murf.ai', 'https://img.tap4.ai/tools/murf.png', 'https://img.tap4.ai/tools/murf-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-voiceover', 'ai-voiceover'),
('playht', 'Play.ht', 'Play.ht is an AI voice generator with ultra-realistic voices. Create voiceovers, podcasts, and audio content.', '## Play.ht\n\nPlay.ht generates ultra-realistic AI voices.\n\n### Key Features\n- 800+ AI voices\n- Voice cloning\n- Multi-language\n- API access\n- Podcast creation\n\n### Pricing\n- Free: 5k words\n- Creator: $31.20/month\n- Pro: $49.50/month', 'https://play.ht', 'https://img.tap4.ai/tools/playht.png', 'https://img.tap4.ai/tools/playht-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'ai-voiceover', 'ai-voiceover'),
('speechify', 'Speechify', 'Speechify is an AI text-to-speech tool. Convert text to natural-sounding voiceovers for video content.', '## Speechify\n\nSpeechify is a powerful AI voice tool.\n\n### Key Features\n- Natural AI voices\n- 30+ languages\n- Voice customization\n- Video integration\n\n### Pricing\n- Free: limited\n- Premium: $11.99/month', 'https://speechify.com', 'https://img.tap4.ai/tools/speechify.png', 'https://img.tap4.ai/tools/speechify-thumb.png', '{"pricing":"Freemium","platform":"Web,Mobile"}', NOW(), 8, 'ai-voiceover', 'ai-voiceover'),
('lovo', 'LOVO AI', 'LOVO is an AI voice generator and text-to-speech platform. Create professional voiceovers with Genny, their AI voice creator.', '## LOVO AI\n\nLOVO generates AI voices for content creators.\n\n### Key Features\n- 500+ AI voices\n- 100+ languages\n- Voice cloning\n- Emotion control\n\n### Pricing\n- Free: 20 min\n- Basic: $19/month\n- Pro: $36/month', 'https://lovo.ai', 'https://img.tap4.ai/tools/lovo.png', 'https://img.tap4.ai/tools/lovo-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'ai-voiceover', 'ai-voiceover'),
('wellsaid', 'WellSaid Labs', 'WellSaid Labs creates the most realistic AI voiceovers. Perfect for professional video and audio production.', '## WellSaid Labs\n\nWellSaid creates premium AI voiceovers.\n\n### Key Features\n- Ultra-realistic voices\n- Voice team management\n- Pronunciation control\n- API integration\n\n### Pricing\n- Trial: 7 days\n- Creator: $44/month\n- Business: $89/month', 'https://wellsaidlabs.com', 'https://img.tap4.ai/tools/wellsaid.png', 'https://img.tap4.ai/tools/wellsaid-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 7, 'ai-voiceover', 'ai-voiceover');

-- 8. 视频增强 (Video Enhancement)
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('topaz', 'Topaz Video AI', 'Topaz Video AI is the best AI video upscaling and enhancement tool. Upscale, denoise, and restore video quality.', '## Topaz Video AI\n\nTopaz is the gold standard for video enhancement.\n\n### Key Features\n- AI video upscaling (up to 8K)\n- AI denoising\n- Frame interpolation\n- Stabilization\n- Slow motion\n\n### Pricing\n- One-time: $299', 'https://www.topazlabs.com/topaz-video-ai', 'https://img.tap4.ai/tools/topaz.png', 'https://img.tap4.ai/tools/topaz-thumb.png', '{"pricing":"Paid","platform":"Desktop"}', NOW(), 9, 'video-enhancement', 'video-enhancement'),
('hitpaw', 'HitPaw', 'HitPaw is an AI video enhancer that upscales video quality, removes noise, and improves clarity with one click.', '## HitPaw\n\nHitPaw enhances videos with AI.\n\n### Key Features\n- AI upscaling to 4K\n- Denoising\n- Color enhancement\n- Face restoration\n\n### Pricing\n- Monthly: $35.99\n- Yearly: $79.99', 'https://www.hitpaw.com', 'https://img.tap4.ai/tools/hitpaw.png', 'https://img.tap4.ai/tools/hitpaw-thumb.png', '{"pricing":"Paid","platform":"Desktop"}', NOW(), 7, 'video-enhancement', 'video-enhancement'),
('avclabs', 'AVCLabs', 'AVCLabs Video Enhancer AI improves video quality with AI upscaling, denoising, and face refinement.', '## AVCLabs\n\nAVCLabs enhances video quality with AI.\n\n### Key Features\n- AI upscaling\n- Face enhancement\n- Color correction\n- Frame interpolation\n\n### Pricing\n- Monthly: $39.95\n- Yearly: $119.95', 'https://www.avclabs.com', 'https://img.tap4.ai/tools/avclabs.png', 'https://img.tap4.ai/tools/avclabs-thumb.png', '{"pricing":"Paid","platform":"Desktop"}', NOW(), 7, 'video-enhancement', 'video-enhancement'),
('pixop', 'Pixop', 'Pixop is a cloud-based AI video enhancement platform. Upscale and improve video quality in the browser.', '## Pixop\n\nPixop enhances videos in the cloud.\n\n### Key Features\n- Cloud-based upscaling\n- AI denoising\n- Deep restoration\n- Batch processing\n- API access\n\n### Pricing\n- Pay-as-you-go from $0.05/sec', 'https://www.pixop.com', 'https://img.tap4.ai/tools/pixop.png', 'https://img.tap4.ai/tools/pixop-thumb.png', '{"pricing":"Pay-as-you-go","platform":"Web"}', NOW(), 7, 'video-enhancement', 'video-enhancement'),
('tensorpix', 'TensorPix', 'TensorPix is an AI video and image enhancer. Improve video quality with AI-powered filters and upscaling.', '## TensorPix\n\nTensorPix is a popular AI enhancement tool.\n\n### Key Features\n- AI video upscaling\n- AI filters\n- Batch processing\n- Web-based\n\n### Pricing\n- Free: 3 videos/month\n- Starter: $8/month\n- Pro: $19/month', 'https://tensorpix.com', 'https://img.tap4.ai/tools/tensorpix.png', 'https://img.tap4.ai/tools/tensorpix-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'video-enhancement', 'video-enhancement'),
('neural-love', 'Neural Love', 'Neural Love is an AI enhancement platform. Improve video and image quality, upscale, and restore media files.', '## Neural Love\n\nNeural Love enhances media with AI.\n\n### Key Features\n- AI video upscaling\n- Image enhancement\n- Audio enhancement\n- Restoration\n\n### Pricing\n- Free: 5 credits\n- 100 credits: $10\n- 300 credits: $30', 'https://neural.love', 'https://img.tap4.ai/tools/neural-love.png', 'https://img.tap4.ai/tools/neural-love-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 7, 'video-enhancement', 'video-enhancement');