-- ============================================
-- ClipGrove: 插入30+ AI Agent 工具数据
-- ============================================

-- 1. AI Coding Agent
INSERT INTO web_navigation (name, title, content, detail, url, image_url, thumbnail_url, website_data, collection_time, star_rating, tag_name, category_name) VALUES
('claude-code', 'Claude Code', 'Anthropic 推出的终端 AI 编程 Agent，SWE-bench 评分 80.9%，支持大型代码库重构、跨文件批量整改、Git 操作，是当前最强的 AI 编程 Agent。', '## Claude Code\n\nAnthropic 官方 CLI 编程 Agent，多项基准评测领先。\n\n### 核心功能\n- 终端原生 Agent，整库读写、跑测试、Git 操作\n- 长上下文支持超大代码库\n- Agent Teams 多智能体协作\n- 80.9% SWE-bench 评分\n\n### 定价\n- 含于 Claude Pro 订阅 $20/月起\n- Max 档 $100-200/月', 'https://docs.anthropic.com/en/docs/claude-code', 'https://img.tap4.ai/tools/claude.png', 'https://img.tap4.ai/tools/claude-thumb.png', '{"pricing":"Paid","platform":"CLI"}', NOW(), 10, 'coding-agent,anthropic,cli', 'coding-agent'),

('codex-cli', 'OpenAI Codex CLI', 'OpenAI 推出的终端 AI 编程 Agent，支持多智能体并行、云端执行、审计追踪，Terminal-Bench 评分 83.4%。', '## OpenAI Codex CLI\n\nOpenAI 旗舰级 AI 编程 Agent 平台。\n\n### 核心功能\n- 多智能体并行执行\n- 云端沙箱运行\n- 审计追踪\n- 直接操作电脑\n- 长期任务执行\n\n### 定价\n- ChatGPT Plus $20/月\n- Pro $200/月', 'https://github.com/openai/codex', 'https://img.tap4.ai/tools/openai.png', 'https://img.tap4.ai/tools/openai-thumb.png', '{"pricing":"Paid","platform":"CLI"}', NOW(), 10, 'coding-agent,openai,cli', 'coding-agent'),

('cursor', 'Cursor', 'AI 原生 IDE，基于 VS Code，支持多模型切换（Claude、GPT、Gemini），@ 系统精准引用上下文，100万+ 开发者使用。', '## Cursor\n\nAI 原生编程 IDE，500 强企业首选。\n\n### 核心功能\n- @ 系统精准引用文件/文件夹/文档\n- 多模型灵活切换\n- 95ms 自动补全\n- Composer 多文件编辑\n- 1M+ 开发者，估值 $29.3B\n\n### 定价\n- Hobby: 免费\n- Pro: $20/月\n- Pro+: $60/月', 'https://cursor.com', 'https://img.tap4.ai/tools/cursor.png', 'https://img.tap4.ai/tools/cursor-thumb.png', '{"pricing":"Freemium","platform":"Desktop"}', NOW(), 9, 'coding-agent,ide', 'coding-agent'),

('github-copilot', 'GitHub Copilot', 'GitHub 的 AI 编程助手，Agent Mode 自主执行多步编程任务，支持 VS Code/JetBrains/Vim 等多编辑器，性价比最高的付费方案。', '## GitHub Copilot\n\n最广泛的 AI 编码入口，$10/月。\n\n### 核心功能\n- Agent Mode 自主编程\n- PR 审查、Issue 总结\n- 多编辑器支持\n- SOC 2 Type II 认证\n- 多模型（Claude、GPT、Gemini）\n\n### 定价\n- Free: 2000 次/月\n- Pro: $10/月\n- Pro+: $39/月', 'https://github.com/features/copilot', 'https://img.tap4.ai/tools/github.png', 'https://img.tap4.ai/tools/github-thumb.png', '{"pricing":"Freemium","platform":"IDE Extension"}', NOW(), 9, 'coding-agent,github', 'coding-agent'),

('cline', 'Cline', '完全开源的 VS Code 扩展 AI 编程 Agent，支持多模型，5 小时编程约 $6 API 费用，无需订阅。', '## Cline\n\n最强的免费开源 AI 编程 Agent。\n\n### 核心功能\n- 完全开源，免费使用\n- 支持 Anthropic/Gemini/OpenAI 等多模型\n- 终端操作和浏览器访问\n- 多步骤任务编排\n- 完全控制 API 选择\n\n### 定价\n- 免费 + API 费用\n- Teams: $20/用户/月（前 10 席永久免费）', 'https://github.com/cline/cline', 'https://img.tap4.ai/tools/vscode.png', 'https://img.tap4.ai/tools/vscode-thumb.png', '{"pricing":"Free","platform":"IDE Extension"}', NOW(), 9, 'coding-agent,opensource', 'coding-agent'),

('windsurf', 'Windsurf', 'Cognition 推出的 AI 原生 IDE，专注编程体验，$15/月固定费率，Flow State 沉浸式编程体验。', '## Windsurf\n\n注重编程体验的 AI 原生 IDE。\n\n### 核心功能\n- Cascade 智能模式\n- 项目级记忆\n- 5 个并行 Agent\n- 代码库导航流畅\n- 固定费率无限使用\n\n### 定价\n- Free: 有限制\n- Pro: $15/月\n- Business: $30/月', 'https://windsurf.com', 'https://img.tap4.ai/tools/windsurf.png', 'https://img.tap4.ai/tools/windsurf-thumb.png', '{"pricing":"Freemium","platform":"Desktop"}', NOW(), 8, 'coding-agent,ide', 'coding-agent'),

('aider', 'Aider', '开源的终端 AI 结对编程工具，Git 感知，支持任何 LLM，多文件编辑，自动生成 commit。', '## Aider\n\n开源 AI 结对编程利器。\n\n### 核心功能\n- Git 原生感知\n- 支持任何 LLM\n- 多文件编辑\n- 自动生成 commit\n- 代码地图优化\n\n### 定价\n- 免费 + API 费用', 'https://github.com/paul-gauthier/aider', 'https://img.tap4.ai/tools/terminal.png', 'https://img.tap4.ai/tools/terminal-thumb.png', '{"pricing":"Free","platform":"CLI"}', NOW(), 8, 'coding-agent,opensource,cli', 'coding-agent'),

('gemini-cli', 'Gemini CLI', 'Google 官方开源终端 Agent，2026 年 4 月发布，ReAct 循环，100 万 token 上下文，MCP 支持，Apache 2.0 许可。', '## Gemini CLI\n\nGoogle 官方的开源终端 AI Agent。\n\n### 核心功能\n- ReAct 推理循环\n- 100 万 token 上下文\n- MCP 协议支持\n- Apache 2.0 开源\n- 免费使用 Google 账号\n\n### 定价\n- 免费（需 Google 账号）', 'https://github.com/google-gemini/gemini-cli', 'https://img.tap4.ai/tools/gemini.png', 'https://img.tap4.ai/tools/gemini-thumb.png', '{"pricing":"Free","platform":"CLI"}', NOW(), 8, 'coding-agent,google,opensource,cli', 'coding-agent'),

('roocode', 'RooCode', 'Cline 的分支版本，结构化模式，减少幻觉，支持更多定制化的工作流。', '## RooCode\n\nCline 的增强分支。\n\n### 核心功能\n- 结构化模式\n- 减少 AI 幻觉\n- 自定义工作流\n- 多模型支持\n\n### 定价\n- 免费 + API 费用', 'https://github.com/RooVetGit/Roo-Code', 'https://img.tap4.ai/tools/vscode.png', 'https://img.tap4.ai/tools/vscode-thumb.png', '{"pricing":"Free","platform":"IDE Extension"}', NOW(), 7, 'coding-agent,opensource', 'coding-agent'),

-- 2. Autonomous Agent
('devin', 'Devin', 'Cognition 推出的完全自主 AI 软件工程师，云端沙箱运行，Devin 2.0 支持交互式规划，可独立完成复杂开发任务。', '## Devin\n\n全球首个完全自主 AI 软件工程师。\n\n### 核心功能\n- 完全自主编程\n- 云端沙箱环境\n- 交互式规划\n- 独立完成 PR\n- 调试和测试\n\n### 定价\n- $20/月 + ACU 积分', 'https://devin.ai', 'https://img.tap4.ai/tools/devin.png', 'https://img.tap4.ai/tools/devin-thumb.png', '{"pricing":"Paid","platform":"Cloud"}', NOW(), 9, 'autonomous-agent', 'autonomous-agent'),

('openhands', 'OpenHands', '开源自主 AI 软件工程师（原 OpenDevin），可自主解决 GitHub Issue，支持多种 LLM。', '## OpenHands\n\n开源自主 AI 软件工程师。\n\n### 核心功能\n- 自主解决 GitHub Issue\n- 多 LLM 支持\n- 云端 + 本地运行\n- 交互式 Web UI\n\n### 定价\n- 免费开源', 'https://github.com/All-Hands-AI/OpenHands', 'https://img.tap4.ai/tools/openhands.png', 'https://img.tap4.ai/tools/openhands-thumb.png', '{"pricing":"Free","platform":"Cloud/Web"}', NOW(), 8, 'autonomous-agent,opensource', 'autonomous-agent'),

('swe-agent', 'SWE-Agent', '普林斯顿大学开发的自主编程 Agent，可自主解决真实 GitHub Issue，学术前沿。', '## SWE-Agent\n\n普林斯顿 NLP 组开发的自主编程 Agent。\n\n### 核心功能\n- 自主解决 GitHub Issue\n- 基于 LM 的 Agent 架构\n- 学术研究前沿\n- 开源免费\n\n### 定价\n- 免费开源', 'https://github.com/princeton-nlp/SWE-agent', 'https://img.tap4.ai/tools/princeton.png', 'https://img.tap4.ai/tools/princeton-thumb.png', '{"pricing":"Free","platform":"CLI"}', NOW(), 8, 'autonomous-agent,opensource,research', 'autonomous-agent'),

('manus', 'Manus', '被 Meta 收购的自主数字员工 Agent，浏览器扩展，可自动完成各类在线任务。', '## Manus\n\nMeta 收购的自主数字员工平台。\n\n### 核心功能\n- 自主浏览器操作\n- 多步骤任务执行\n- 浏览器扩展\n- 数字员工概念\n\n### 定价\n- 免费/付费', 'https://manus.im', 'https://img.tap4.ai/tools/manus.png', 'https://img.tap4.ai/tools/manus-thumb.png', '{"pricing":"Freemium","platform":"Browser Extension"}', NOW(), 8, 'autonomous-agent,browser', 'autonomous-agent'),

('operator', 'OpenAI Operator', 'ChatGPT 的自主 Web Agent，使用 CUA 技术，可自动完成网页操作，有人类检查点。', '## OpenAI Operator\n\nChatGPT 的自主 Web 操作 Agent。\n\n### 核心功能\n- CUA 技术驱动\n- 自动网页操作\n- 人类检查点\n- 多步骤任务\n\n### 定价\n- ChatGPT Pro 订阅', 'https://operator.chatgpt.com', 'https://img.tap4.ai/tools/openai.png', 'https://img.tap4.ai/tools/openai-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 8, 'autonomous-agent,browser,openai', 'autonomous-agent'),

-- 3. Agent Framework
('langchain', 'LangChain', '最流行的 AI Agent 开发框架，模块化架构，支持记忆、工具链、多步推理，Python/JS 双语言。', '## LangChain\n\n使用最广泛的 AI Agent 框架。\n\n### 核心功能\n- 模块化 Agent 架构\n- 记忆管理\n- 工具链集成\n- RAG 支持\n- Python + JS\n\n### 定价\n- 免费开源', 'https://github.com/langchain-ai/langchain', 'https://img.tap4.ai/tools/langchain.png', 'https://img.tap4.ai/tools/langchain-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 9, 'agent-framework,opensource,python', 'agent-framework'),

('crewai', 'CrewAI', '多 Agent 角色协作框架，60%+ 世界 500 强使用，支持定义角色、目标和工具的角色扮演 Agent 团队。', '## CrewAI\n\n基于角色的多 Agent 协作框架。\n\n### 核心功能\n- 角色定义与分配\n- 多 Agent 协作\n- 目标驱动\n- 工具集成\n- 60%+ 500 强使用\n\n### 定价\n- 免费开源', 'https://github.com/crewAIInc/crewAI', 'https://img.tap4.ai/tools/crewai.png', 'https://img.tap4.ai/tools/crewai-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 9, 'agent-framework,opensource,python', 'agent-framework'),

('autogen', 'AutoGen', '微软推出的多 Agent 对话框架，支持 Agent 间自动对话、代码生成和执行。', '## AutoGen\n\n微软多 Agent 对话框架。\n\n### 核心功能\n- 多 Agent 自动对话\n- 代码生成和执行\n- 人机协作\n- 可定制 Agent\n\n### 定价\n- 免费开源', 'https://github.com/microsoft/autogen', 'https://img.tap4.ai/tools/microsoft.png', 'https://img.tap4.ai/tools/microsoft-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 8, 'agent-framework,microsoft,opensource,python', 'agent-framework'),

('autogpt', 'AutoGPT', 'AI Agent 先驱，现已发展为完整的可视化平台，支持自主思考、自动执行、浏览器操作。', '## AutoGPT\n\nAI Agent 鼻祖，现已发展为完整平台。\n\n### 核心功能\n- 自主思考和执行\n- 可视化构建器\n- 浏览器操作\n- 插件生态\n\n### 定价\n- 免费开源', 'https://github.com/Significant-Gravitas/AutoGPT', 'https://img.tap4.ai/tools/autogpt.png', 'https://img.tap4.ai/tools/autogpt-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 8, 'agent-framework,opensource,python', 'agent-framework'),

('dify', 'Dify', '开源 LLMOps 平台，可视化 Agent 构建器，RAG 支持，130k+ GitHub Stars，可自托管。', '## Dify\n\n开源 LLM 应用开发平台。\n\n### 核心功能\n- 可视化 Agent 构建\n- RAG 管道\n- 工作流编排\n- 可自托管\n- 130k+ Stars\n\n### 定价\n- 免费开源 + Cloud', 'https://github.com/langgenius/dify', 'https://img.tap4.ai/tools/dify.png', 'https://img.tap4.ai/tools/dify-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 9, 'agent-framework,opensource,lowcode', 'agent-framework'),

('openai-agents-sdk', 'OpenAI Agents SDK', 'OpenAI 官方 Agent 开发 SDK，支持多步骤 Agent、handoff 交接、沙箱运行，2026 年 3 月 GA。', '## OpenAI Agents SDK\n\nOpenAI 官方 Agent 开发工具包。\n\n### 核心功能\n- 多步骤 Agent\n- Agent handoff 交接\n- 沙箱运行环境\n- 跨 7 家模型提供商\n- 2026 年 3 月 GA\n\n### 定价\n- 免费开源', 'https://github.com/openai/openai-agents-python', 'https://img.tap4.ai/tools/openai.png', 'https://img.tap4.ai/tools/openai-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 8, 'agent-framework,openai,opensource,python', 'agent-framework'),

('google-adk', 'Google ADK', 'Google Agent Development Kit，原生 Gemini 支持，多 Agent 编排，Python/TS/Java/Go 四语言。', '## Google ADK\n\nGoogle 官方 Agent 开发工具包。\n\n### 核心功能\n- 原生 Gemini 集成\n- 多 Agent 编排\n- Python + TS + Java + Go\n- 唯一支持 Java 和 Go 的框架\n\n### 定价\n- 免费开源', 'https://github.com/google/adk-python', 'https://img.tap4.ai/tools/gemini.png', 'https://img.tap4.ai/tools/gemini-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 7, 'agent-framework,google,opensource', 'agent-framework'),

-- 4. Browser Agent
('browser-use', 'Browser Use', '开源的浏览器 Agent 库，被 Manus 使用，支持多标签页、视觉识别、自主操作网页。', '## Browser Use\n\n最流行的开源浏览器 Agent 库。\n\n### 核心功能\n- 多标签页管理\n- 视觉识别\n- 自主网页操作\n- 被 Manus 采用\n- Python 开发\n\n### 定价\n- 免费开源', 'https://github.com/browser-use/browser-use', 'https://img.tap4.ai/tools/browser.png', 'https://img.tap4.ai/tools/browser-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 9, 'browser-agent,opensource,python', 'browser-agent'),

('playwright-mcp', 'Playwright MCP', '微软官方 Playwright MCP Server，为 AI Agent 提供浏览器自动化能力，MCP 协议标准。', '## Playwright MCP\n\n微软官方浏览器自动化 MCP Server。\n\n### 核心功能\n- MCP 协议标准\n- 浏览器自动化\n- AI Agent 集成\n- 截图和调试\n\n### 定价\n- 免费开源', 'https://github.com/microsoft/playwright-mcp', 'https://img.tap4.ai/tools/microsoft.png', 'https://img.tap4.ai/tools/microsoft-thumb.png', '{"pricing":"Free","platform":"MCP Server"}', NOW(), 8, 'browser-agent,microsoft,opensource,mcp', 'browser-agent'),

('skyvern', 'Skyvern', '视觉驱动的浏览器自动化 Agent，使用 GPT-4V 导航，无需编程选择器，开箱即用。', '## Skyvern\n\n视觉驱动的浏览器自动化。\n\n### 核心功能\n- GPT-4V 视觉导航\n- 无需编程选择器\n- 自动化工作流\n- 开源\n\n### 定价\n- 免费开源', 'https://github.com/Skyvern-AI/skyvern', 'https://img.tap4.ai/tools/skyvern.png', 'https://img.tap4.ai/tools/skyvern-thumb.png', '{"pricing":"Free","platform":"Framework"}', NOW(), 7, 'browser-agent,opensource,vision', 'browser-agent'),

('multion', 'MultiOn', '可靠的 Web 自动化 API，处理验证码，支持复杂网页交互，企业级可靠性。', '## MultiOn\n\n企业级 Web 自动化 API。\n\n### 核心功能\n- 验证码处理\n- 复杂网页交互\n- API 接口\n- 企业级可靠性\n\n### 定价\n- 按用量付费', 'https://multion.ai', 'https://img.tap4.ai/tools/multion.png', 'https://img.tap4.ai/tools/multion-thumb.png', '{"pricing":"Paid","platform":"API"}', NOW(), 7, 'browser-agent,api', 'browser-agent'),

-- 5. Workflow Agent
('n8n', 'n8n', '开源工作流自动化平台，内置 AI Agent 节点，可视化 + 代码双模式，700+ 集成。', '## n8n\n\n开源工作流自动化 + AI Agent。\n\n### 核心功能\n- 可视化工作流构建\n- 内置 AI Agent 节点\n- 700+ 应用集成\n- 代码 + 可视化双模式\n- 可自托管\n\n### 定价\n- 免费开源 + Cloud', 'https://github.com/n8n-io/n8n', 'https://img.tap4.ai/tools/n8n.png', 'https://img.tap4.ai/tools/n8n-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 9, 'workflow-agent,opensource,automation', 'workflow-agent'),

('zapier-ai', 'Zapier AI', '7000+ 应用集成的工作流自动化平台，自然语言创建工作流，最广泛的集成生态。', '## Zapier AI\n\n最大的工作流自动化平台。\n\n### 核心功能\n- 7000+ 应用集成\n- 自然语言创建工作流\n- AI 自动化\n- 企业级\n\n### 定价\n- 从 $19.99/月', 'https://zapier.com/ai', 'https://img.tap4.ai/tools/zapier.png', 'https://img.tap4.ai/tools/zapier-thumb.png', '{"pricing":"Paid","platform":"Web"}', NOW(), 8, 'workflow-agent,automation', 'workflow-agent'),

('make', 'Make', '可视化工作流平台，支持 AI 功能，拖拽式构建自动化流程，丰富的模板库。', '## Make\n\n强大的可视化工作流平台。\n\n### 核心功能\n- 拖拽式工作流构建\n- AI 功能集成\n- 丰富的模板\n- 定时任务\n\n### 定价\n- 免费 + 付费', 'https://make.com', 'https://img.tap4.ai/tools/make.png', 'https://img.tap4.ai/tools/make-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'workflow-agent,automation', 'workflow-agent'),

('bolt-new', 'Bolt.new', '浏览器内 AI 全栈应用构建器，输入提示词即可生成完整 Web 应用，适合快速原型开发。', '## Bolt.new\n\nAI 驱动的全栈应用构建器。\n\n### 核心功能\n- 提示词生成完整应用\n- 浏览器内运行\n- 全栈支持\n- 即时部署\n\n### 定价\n- 免费/付费', 'https://bolt.new', 'https://img.tap4.ai/tools/bolt.png', 'https://img.tap4.ai/tools/bolt-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'workflow-agent,app-builder', 'workflow-agent'),

('lovable', 'Lovable', '从聊天描述到构建到部署的一站式 AI 应用构建平台，非开发者也能快速创建应用。', '## Lovable\n\n描述即构建的 AI 应用平台。\n\n### 核心功能\n- 聊天式描述创建应用\n- 自动构建和部署\n- 全栈支持\n- 实时预览\n\n### 定价\n- 免费/$20/月', 'https://lovable.dev', 'https://img.tap4.ai/tools/lovable.png', 'https://img.tap4.ai/tools/lovable-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'workflow-agent,app-builder', 'workflow-agent'),

('replit-agent', 'Replit Agent', 'Replit 的 AI Agent，从提示词生成全栈应用并自动部署，浏览器内完整开发环境。', '## Replit Agent\n\nReplit 的 AI 全栈开发 Agent。\n\n### 核心功能\n- 提示词生成全栈应用\n- 自动部署\n- 浏览器内 IDE\n- 实时协作\n\n### 定价\n- 免费/$25/月', 'https://replit.com', 'https://img.tap4.ai/tools/replit.png', 'https://img.tap4.ai/tools/replit-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'workflow-agent,app-builder', 'workflow-agent'),

('v0', 'v0 by Vercel', 'Vercel 推出的 AI 前端组件生成器，提示词生成 React/Tailwind 组件，直接复制使用。', '## v0\n\nVercel 的 AI 前端生成器。\n\n### 核心功能\n- 提示词生成 React 组件\n- Tailwind CSS 样式\n- 直接复制代码\n- 迭代优化\n\n### 定价\n- 免费/Pro', 'https://v0.dev', 'https://img.tap4.ai/tools/vercel.png', 'https://img.tap4.ai/tools/vercel-thumb.png', '{"pricing":"Freemium","platform":"Web"}', NOW(), 8, 'workflow-agent,app-builder', 'workflow-agent'),

('sourcegraph-cody', 'Sourcegraph Cody', '专为大型代码库设计的 AI 编程助手，企业级上下文引擎，代码搜索和智能问答。', '## Sourcegraph Cody\n\n大型代码库 AI 编程助手。\n\n### 核心功能\n- 企业级上下文引擎\n- 大型代码库理解\n- 代码搜索\n- 智能问答\n\n### 定价\n- 免费/$9/月', 'https://sourcegraph.com/cody', 'https://img.tap4.ai/tools/sourcegraph.png', 'https://img.tap4.ai/tools/sourcegraph-thumb.png', '{"pricing":"Freemium","platform":"IDE Extension"}', NOW(), 7, 'coding-agent,enterprise', 'coding-agent'),

('augment-code', 'Augment Code', '专为企业级大型代码库设计的 AI 编程工具，70.6% SWE-bench，支持 40 万+ 文件代码库。', '## Augment Code\n\n企业级大型代码库 AI 编程。\n\n### 核心功能\n- 40 万+ 文件代码库支持\n- 70.6% SWE-bench\n- 企业定制\n- 深度上下文理解\n\n### 定价\n- 企业定制', 'https://augmentcode.com', 'https://img.tap4.ai/tools/augment.png', 'https://img.tap4.ai/tools/augment-thumb.png', '{"pricing":"Paid","platform":"IDE Extension"}', NOW(), 7, 'coding-agent,enterprise', 'coding-agent');